### ISSUE TITLE
Problem in SimpleGraphRepositoryImpl

### ISSUE THREAD

**Issue by drseb** [vaadin/Graph-Explorer-demo#9]
Hi,

it seems to me that the method 

      public ArcImpl joinNodes(String nid1, String nid2, String eid, String label) {

creates an edge from nid2 to nid1. But then the node with the outgoing edge is node 'nid2' and the one with the incoming edge is 'nid1'. Thus I think that the following lines

    addToOutgoing(nid1, eid);
    addToIncomming(nid2, eid);

should be 

    addToOutgoing(nid2, eid);
    addToIncomming(nid1, eid);

Or do I understand something wrong?

Best,
Sebastian

**Comment by marlonrichert** [comment]
There is no SimpleGraphRepositoryImpl in the master branch Graph-Explorer-demo repository. Please file your issue in the correct place.
